// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88LLgiApUud0ppaI0q8vCoGWPgXwZ6HA',
    appId: '1:806716822443:web:27e32c61adcaec8d0d38ee',
    messagingSenderId: '806716822443',
    projectId: 'iti-task-632f8',
    authDomain: 'iti-task-632f8.firebaseapp.com',
    storageBucket: 'iti-task-632f8.appspot.com',
    measurementId: 'G-13701M67F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsM14Yqjp3N0qON9j_fcKY7OCH0DNN_aE',
    appId: '1:806716822443:android:acc8b7b4aaf4b5ce0d38ee',
    messagingSenderId: '806716822443',
    projectId: 'iti-task-632f8',
    storageBucket: 'iti-task-632f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6YPX210vK6A2iJdrhDu0xTkElF6j1R4w',
    appId: '1:806716822443:ios:939580c5cbc1e1e00d38ee',
    messagingSenderId: '806716822443',
    projectId: 'iti-task-632f8',
    storageBucket: 'iti-task-632f8.appspot.com',
    iosClientId: '806716822443-j2l524h0uj7v2880071nplcqi4ks972l.apps.googleusercontent.com',
    iosBundleId: 'com.example.courses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6YPX210vK6A2iJdrhDu0xTkElF6j1R4w',
    appId: '1:806716822443:ios:d0af3dfa108459390d38ee',
    messagingSenderId: '806716822443',
    projectId: 'iti-task-632f8',
    storageBucket: 'iti-task-632f8.appspot.com',
    iosClientId: '806716822443-uno86t6tjvf5sg6a71ahfc18r2tp1tfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.courses.RunnerTests',
  );
}
